import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "keen-slider/keen-slider.min.css";
import Image from "next/image";
import Link from "next/link";
import React from "react";
import { RotatingBanner } from "./page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <RotatingBanner />
        <header className="w-full bg-white flex flex-col items-center border-b border-gray-200">
          <div className="w-full max-w-6xl flex flex-col md:flex-row items-center justify-between py-4 px-4 md:px-0">
            <div className="flex items-center gap-4">
              <Image src="/logo.png" alt="Comptoir des Services logo" width={180} height={180} priority />
            </div>
            <span className="text-lg md:text-2xl font-semibold text-violet-700 text-center md:text-right mt-4 md:mt-0">
              Votre partenaire pour la veille, l’analyse et la réussite de vos projets
            </span>
          </div>
          <nav className="w-full bg-gradient-to-r from-blue-500 via-violet-500 to-pink-500 shadow">
            <div className="max-w-6xl mx-auto flex flex-wrap justify-center md:justify-start gap-2 md:gap-8 py-3 px-2">
              <Link href="/" className="uppercase text-white font-bold tracking-wide px-3 py-1 hover:bg-white/10 rounded transition">Accueil</Link>
              <Link href="/a-propos" className="uppercase text-white font-bold tracking-wide px-3 py-1 hover:bg-white/10 rounded transition">À propos</Link>
              <Link href="/services" className="uppercase text-white font-bold tracking-wide px-3 py-1 hover:bg-white/10 rounded transition">Nos services</Link>
              <Link href="/blog" className="uppercase text-white font-bold tracking-wide px-3 py-1 hover:bg-white/10 rounded transition">Blog</Link>
              <Link href="/contact" className="uppercase text-white font-bold tracking-wide px-3 py-1 hover:bg-white/10 rounded transition">Contact</Link>
            </div>
          </nav>
        </header>
        {children}
        <footer className="w-full bg-gray-900 text-white py-16 px-4 mt-8">
          <div className="max-w-6xl mx-auto grid grid-cols-1 md:grid-cols-3 gap-12">
            {/* Colonne 1 : Contacts */}
            <div>
              <h3 className="text-xl font-bold mb-4">Contact</h3>
              <ul className="space-y-3 text-gray-300">
                <li className="flex items-center gap-2">
                  <span className="text-lg">📍</span>
                  <span>Abidjan, Côte d&apos;Ivoire</span>
                </li>
                <li className="flex items-center gap-2">
                  <span className="text-lg">✉️</span>
                  <a href="mailto:contact@comptoir-services.ci" className="hover:underline text-gray-100">contact@comptoir-services.ci</a>
                </li>
                <li className="flex items-center gap-2">
                  <span className="text-lg">📞</span>
                  <a href="tel:+2250102030405" className="hover:underline text-gray-100">+225 01 02 03 04 05</a>
                </li>
              </ul>
            </div>
            {/* Colonne 2 : Services */}
            <div>
              <h3 className="text-xl font-bold mb-4">Nos services</h3>
              <ul className="space-y-2 text-gray-300">
                <li>Conseil stratégique</li>
                <li>Veille & analyse de marché</li>
                <li>Formation professionnelle</li>
                <li>Développement de politiques publiques</li>
                <li>Rapports & Analyses</li>
                <li>Réussite client</li>
              </ul>
            </div>
            {/* Colonne 3 : Newsletter */}
            <div>
              <h3 className="text-xl font-bold mb-4">Newsletter</h3>
              <p className="mb-4 text-gray-300">Recevez nos actualités, analyses et conseils directement dans votre boîte mail.</p>
              <form className="flex flex-col sm:flex-row gap-2">
                <input
                  type="email"
                  placeholder="Votre email"
                  className="px-4 py-2 rounded-md bg-white text-black border border-gray-300 focus:outline-none flex-1"
                  required
                />
                <button
                  type="submit"
                  className="bg-gradient-to-r from-blue-500 via-violet-500 to-pink-500 px-6 py-2 rounded-md font-semibold hover:scale-105 transition-transform text-white"
                >
                  S&apos;inscrire
                </button>
              </form>
              {/* Réseaux sociaux */}
              <div className="flex gap-4 mt-6 justify-center">
                <a href="https://facebook.com" target="_blank" rel="noopener noreferrer" aria-label="Facebook" className="hover:scale-110 transition-transform">
                  {/* ... SVG ... */}
                </a>
                <a href="https://wa.me/" target="_blank" rel="noopener noreferrer" aria-label="WhatsApp" className="hover:scale-110 transition-transform">
                  {/* ... SVG ... */}
                </a>
                <a href="https://twitter.com" target="_blank" rel="noopener noreferrer" aria-label="Twitter" className="hover:scale-110 transition-transform">
                  {/* ... SVG ... */}
                </a>
                <a href="https://linkedin.com" target="_blank" rel="noopener noreferrer" aria-label="LinkedIn" className="hover:scale-110 transition-transform">
                  {/* ... SVG ... */}
                </a>
              </div>
            </div>
          </div>
          <div className="mt-12 text-center text-gray-500 text-sm">
            © {new Date().getFullYear()} Comptoir des Services. Tous droits réservés.
          </div>
        </footer>
      </body>
    </html>
  );
}
